# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker images (docker-compose)
          command: docker-compose -f ./docker-compose.yaml build --compress --force-rm --no-cache --pull --parallel
      - run:
          name: View docker images
          command: docker images -a
      - run:
          name: Save nodejs Docker image
          command: docker save -o ./${PROJECT_NAME}_nodejs.tar project_nodejs
      - persist_to_workspace:
          root: .
          paths:
            - ./*.tar
  upload-latest:
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load saved nodejs image
          command: docker load -i /tmp/workspace/${PROJECT_NAME}_nodejs.tar
      - run:
          name: View docker images
          command: docker images -a
      - run:
          name: Rename nodejs image
          command: docker tag project_nodejs floberrot/projet1-team4}_nodejs:latest
      - run:
          name: Publish Node Image to Docker Hub
          command: |
            docker login -u floberrot --password 9DMc79J3N+:8#gc
            docker push floberrot/projet1-team4_nodejs:latest
