version: 2.1
executors:
  mypublisher:
    environment:
      PROJECT_NAME: projet1-team4
      USER: "floberrot"
      PASS: "9DMc79J3N+:8#gc"
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    executor: mypublisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build project docker (command docker-compose build)
          command: docker-compose -f docker-compose.yml build --force
      - run:
          name: Docker image in the prject
          command: docker images -a
      - run:
          name: docker save allow to save node.js image
          command: docker save -o ./${PROJECT_NAME}_nodejs.tar project_nodejs
      - persist_to_workspace:
          root: .
          paths:
            - ./*.tar
  upload-latest:
    executor: mypublisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load docker node.js that we save before 
          command: docker load -i /tmp/workspace/${PROJECT_NAME}_nodejs.tar
      - run:
          name: Display our docker image
          command: docker images -a
      - run:
          name: Name our project with our login and project name
          command: docker tag project_nodejs floberrot/${PROJECT_NAME}_nodejs:latest
      - run:
          name: Publish To Docker Hub our docker image
          command: |
            docker login -u $USER --password $PASS
            docker push floberrot/${PROJECT_NAME}_nodejs:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - upload-latest:
          requires:
            - build
          filters:
            branches:
              only: master
