version: 2.1
executors:
  mypublisher:
    environment:
      PROJECT_NAME: projet1-team4
      USER: "floberrot"
      PASS: "9DMc79J3N+:8#gc"
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    executor: mypublisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build de notre projet avec la commande docker-compose
          command: docker-compose -f docker-compose.yml build --force
      - run:
          name: Récupère nos images dans le projet
          command: docker images -a
      - run:
          name: Sauvegarde l'image docker node js 
          command: docker save -o ./${PROJECT_NAME}_nodejs.tar project_nodejs
      - persist_to_workspace:
          root: .
          paths:
            - ./*.tar
  publish-on-docker:
    executor: mypublisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Charge le docker de node js de notre projet 
          command: docker load -i /tmp/workspace/${PROJECT_NAME}_nodejs.tar
      - run:
          name: Affiche les docker images
          command: docker images -a
      - run:
          name: Donne un nom a notre projet sur Docker HUB
          command: docker tag project_nodejs floberrot/${PROJECT_NAME}_nodejs:latest
      - run:
          name: Publication sur notre docker HUB
          command: |
            docker login -u $USER --password $PASS
            docker push floberrot/${PROJECT_NAME}_nodejs:latest
workflows:
  version: 2.1
  build-publication:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-on-docker:
          requires:
            - build
          filters:
            branches:
              only: master
